name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        run: |
          cd dist
          git config --global user.email "deploymentbot@thisisjonathan.com"
          git config --global user.name "Deployment Bot"
          git init
          git add :/
          git commit -m "Deploy build"
          git checkout -b gh-pages
          git remote add origin "https://jonathanlloyd:${{ secrets.GITHUB_TOKEN }}@github.com/jonathanlloyd/3d-engine.git"
          git push -f origin HEAD
